webtrack.pdf: Web_Tracking_Elgg.tex Web_Environment_PartI_Elgg.tex header.tex
	pdflatex -jobname=webtrack Web_Tracking_Elgg
	pdflatex -jobname=webtrack Web_Tracking_Elgg

clean:
	rm -fr auto
	rm -f *.aux *.log *.dvi *.pdf
