FROM mfthomps/labtainer.network
MAINTAINER jkhosali@nps.edu
ARG lab
ARG labdir
ARG imagedir

ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz $HOME

ENTRYPOINT sudo /sbin/faux_init && bash
