FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
LABEL description="This is base Docker image for Parameterized labs"

ARG lab
ARG labdir
ARG imagedir
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-client \
    openssh-server \
    openvpn

ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
ENV HOME /home/ubuntu
RUN echo "cd" >> /home/ubuntu/.profile
RUN echo "" > /home/ubuntu/.bash_logout

