FROM ubuntu:xenial
FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
LABEL description="This is base Docker image for Parameterized labs"

ARG lab
ARG labdir
ARG imagedir
RUN apt-get update && apt-get install -y --no-install-recommends \
    tcpdump
# tcpdump fails to run if in /usr/sbin 
RUN sudo mv /usr/sbin/tcpdump /usr/bin/tcpdump

USER ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
ENV HOME /home/ubuntu
RUN echo "cd" >> /home/ubuntu/.profile
RUN echo "" > /home/ubuntu/.bash_logout

