FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
LABEL description="This is base Docker image for Parameterized labs"

ARG lab
ARG labdir
ARG imagedir
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-client \
    wget \
    openvpn 

USER ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
ENV HOME /home/ubuntu

