FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
ARG lab
ARG labdir
ARG imagedir
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-client \
    wget \
    openvpn 


ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz $HOME
RUN echo "cd" >> $HOME/.profile
RUN echo "source $HOME/.local/bin/startup.sh" >> $HOME/.profile
RUN echo "" > $HOME/.bash_logout
ENTRYPOINT sudo /sbin/faux_init && bash
