FROM mfthomps/labtainer.base
#FROM mfthomps/labtainer.network
ARG lab
ARG labdir
ARG imagedir
ARG apt_source
RUN sed -i s/archive.ubuntu.com/$apt_source/ /etc/apt/sources.list

RUN apt-get update && apt-get install -y --no-install-recommends nmap
RUN apt-get update && apt-get install -y --no-install-recommends telnet

ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
