FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
LABEL description="This is base Docker image for Parameterized labs"

ARG lab
ARG labdir
ARG imagedir
RUN apt-get update && apt-get install -y --no-install-recommends \
    telnetd \
    update-inetd \
    xinetd

ADD $labdir/config/telnet /etc/xinetd.d/

USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu


ENTRYPOINT sudo service xinetd restart && bash
