FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
LABEL description="This is base Docker image for Parameterized labs"

ARG lab
ARG labdir
ARG imagedir
ADD $labdir/$lab.tar.gz /home/ubuntu
RUN apt-get update && apt-get install -y --no-install-recommends telnet
ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ENV HOME /home/ubuntu
RUN echo "cd" >> /home/ubuntu/.profile
RUN echo "" > /home/ubuntu/.bash_logout

