wireshark-intro.pdf: wireshark-intro.tex header.tex
	pdflatex -jobname=wireshark-intro wireshark-intro
	pdflatex -jobname=wireshark-intro wireshark-intro

clean:
	rm -fr auto
	rm -f *.aux *.log *.pdf *.dvi *.out
