FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
ARG lab
ARG labdir
ARG imagedir
ADD bin/funbuffer /usr/bin/
RUN apt-get update && apt-get install -y --no-install-recommends wget

USER ubuntu
ADD $labdir/$lab.tar.gz /home/ubuntu
ENV HOME /home/ubuntu
RUN echo "cd" >> /home/ubuntu/.profile
RUN echo "source /home/ubuntu/.local/bin/startup.sh" >> /home/ubuntu/.profile
RUN echo "" > /home/ubuntu/.bash_logout

