/*******************************************/
/*     FILE GENERATED BY iec2c             */
/* Editing this file is not recommended... */
/*******************************************/

#include "iec_std_lib.h"

// RESOURCE RES0

extern unsigned long long common_ticktime__;

#include "accessor.h"
#include "POUS.h"

#include "Config0.h"

#include "POUS.c"

BOOL MAIN;
PROG0 RES0__INST0;
#define INST0 RES0__INST0

void RES0_init__(void) {
  BOOL retain;
  retain = 0;
  
  MAIN = __BOOL_LITERAL(FALSE);
  PROG0_init__(&INST0,retain);
}

void RES0_run__(unsigned long tick) {
  MAIN = !(tick % 1);
  if (MAIN) {
    PROG0_body__(&INST0);
  }
}

