#!/bin/bash

cat /etc/motd

#
# Docker on window manages to screw this up 
#
echo labtainer | sudo -S chown root:docker /var/run/docker.sock
mkdir -p /tmp/labtainer
echo labtainer | sudo -S chown labtainer:labtainer /tmp/labtainer

/wait-for-it.sh $VNCHOST:5901 > /tmp/waitforit.log 2>&1

export LABTAINER_DIR=/home/labtainer/labtainer/trunk
/home/labtainer/.doterm.sh > /dev/null 2>&1
while true
do
    sleep 2000
done
