#!/bin/bash

cat /etc/motd

#
# Docker on window manages to screw this up 
#
echo labtainer | sudo -S chown root:docker /var/run/docker.sock
mkdir -p /tmp/labtainer
echo labtainer | sudo -S chown labtainer:labtainer /tmp/labtainer

export LABTAINER_DIR=/home/labtainer/labtainer/trunk
/home/labtainer/.doterm.sh > /dev/null 2>&1
while true
do
    sleep 5
    got_term=$(ps aux | grep [g]nome-terminal)
    if [ -z "$got_term" ]; then
        echo "failed terminal, try again" >>/tmp/termfail.log
        /home/labtainer/.doterm.sh > /dev/null 2>&1
    else
        break
    fi
done
while true
do
    sleep 2000
done
