/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labtainers.paramsui;
import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.JDialog;
import labtainers.mainui.ToolTipHandlers.ToolTipWrapper;
import labtainers.mainui.ToolTipHandlers.ToolTipWrapper;
import static labtainers.mainui.ToolTipHandlers.setComboItems;
import static labtainers.resultsui.ParamReferenceStorage.Operator_ITEMS;
import labtainers.resultsui.ParamReferenceStorage;

/**
 *
 * @author Daniel Liao
 */
public class ParamPanels extends javax.swing.JPanel {

    static Dimension dim = new Dimension(975, 100);
    ParamsUI uiParam;
    ParamsData dataUI;
    int rowNum;
    String comments="";
    
    /**
     * Creates new form ParamsPanel
     */
    //Creating fresh params line
    public ParamPanels(ParamsUI ui, ArrayList<String> containers, int rowNum) {
        initComponents();
        this.uiParam = ui;
        this.dataUI = ui.data;
        this.rowNum = rowNum;
        
        jLabel3.setText(Integer.toString(rowNum));
        LowerBoundTextField.setVisible(false);
                
        setComboItems(OperationComboBox, Operator_ITEMS);
        System.out.println("num containers "+containers.size());
        ContainerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(containers.toArray(new String[containers.size()])));   
    }

    //Loading params line
    public ParamPanels(ParamsUI ui, ArrayList<String> containers, int rowNum, String paramID, String container, 
              String fileID, String operator, String symbol, 
              String hashedString, String upperBound, String lowerBound){
        initComponents();
        this.uiParam = ui;
        this.dataUI = ui.data;
        this.rowNum = rowNum;
        jLabel3.setText(Integer.toString(rowNum));      
        
        setComboItems(OperationComboBox, Operator_ITEMS);
        ContainerComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(containers.toArray(new String[containers.size()])));
        
        //Set Values
        setContainerComboBox(container);       
        setOperatorComboBox(operator);
        setParamIDTextField(paramID);
        setFileTextField(fileID);        
        setSymbolTextField(symbol);        
        setHashedStringTextField(hashedString);        
        setUpperBoundTextField(upperBound);        
        setLowerBoundTextField(lowerBound);        
 
        this.revalidate();
        this.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        UpButton = new javax.swing.JButton();
        DownButton = new javax.swing.JButton();
        ParamPanel = new javax.swing.JPanel();
        ParamIDTextField = new javax.swing.JTextField();
        OperationComboBox = new javax.swing.JComboBox<>();
        FileNameTextField = new javax.swing.JTextField();
        SymbolTextField = new javax.swing.JTextField();
        LowerBoundTextField = new javax.swing.JTextField();
        UpperBoundTextField = new javax.swing.JTextField();
        HashedStringTextField = new javax.swing.JTextField();
        ContainerComboBox = new javax.swing.JComboBox<>();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(1560, 86));
        setMinimumSize(new java.awt.Dimension(1560, 86));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(1580, 86));

        jLabel3.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        jLabel3.setText("10");

        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        UpButton.setFont(new java.awt.Font("Ubuntu Condensed", 0, 12)); // NOI18N
        UpButton.setText("^");
        UpButton.setMaximumSize(new java.awt.Dimension(19, 50));
        UpButton.setMinimumSize(new java.awt.Dimension(19, 31));
        UpButton.setPreferredSize(new java.awt.Dimension(19, 31));
        UpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpButtonActionPerformed(evt);
            }
        });

        DownButton.setFont(new java.awt.Font("Ubuntu Condensed", 0, 12)); // NOI18N
        DownButton.setText("v");
        DownButton.setToolTipText("");
        DownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DownButtonActionPerformed(evt);
            }
        });

        ParamPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        OperationComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                OperationComboBoxItemStateChanged(evt);
            }
        });
        OperationComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OperationComboBoxActionPerformed(evt);
            }
        });

        FileNameTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "File name"));

        SymbolTextField.setToolTipText("Parameter based on Line Type");
        SymbolTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Symbol"));

        LowerBoundTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        LowerBoundTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Lower bound"));
        LowerBoundTextField.setMinimumSize(new java.awt.Dimension(20, 100));

        UpperBoundTextField.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        UpperBoundTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Upper bound"));
        UpperBoundTextField.setMinimumSize(new java.awt.Dimension(20, 100));

        HashedStringTextField.setToolTipText("Parameter based on Line Type");
        HashedStringTextField.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Hashed string"));

        ContainerComboBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ContainerComboBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout ParamPanelLayout = new javax.swing.GroupLayout(ParamPanel);
        ParamPanel.setLayout(ParamPanelLayout);
        ParamPanelLayout.setHorizontalGroup(
            ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParamPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParamIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ContainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(OperationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(FileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(SymbolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(LowerBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(UpperBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HashedStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        ParamPanelLayout.setVerticalGroup(
            ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ParamPanelLayout.createSequentialGroup()
                .addGroup(ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ParamIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LowerBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SymbolTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(FileNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(UpperBoundTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HashedStringTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ParamPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(OperationComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ContainerComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addComponent(ParamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UpButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ParamPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(jLabel3))
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(UpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DownButton))
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jButton1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void UpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpButtonActionPerformed
         swapUpdate("UP", rowNum-1); //Subtract rowNum by one to get the proper index number
    }//GEN-LAST:event_UpButtonActionPerformed

    private void DownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DownButtonActionPerformed
         swapUpdate("DOWN", rowNum-1); //Subtract rowNum by one to get the proper index number
    }//GEN-LAST:event_DownButtonActionPerformed

    private void OperationComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_OperationComboBoxItemStateChanged
        operatorListener();
    }//GEN-LAST:event_OperationComboBoxItemStateChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        deleteButton();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ContainerComboBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ContainerComboBoxItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ContainerComboBoxItemStateChanged

    private void OperationComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OperationComboBoxActionPerformed
        operatorListener();
    }//GEN-LAST:event_OperationComboBoxActionPerformed
    
    private void deleteButton(){
       JPanel panelOfParams = (JPanel)this.getParent();
       panelOfParams.remove(this);
       uiParam.data.rowCount--;
       uiParam.refresh();
    }
    private void operatorListener(){  
        ToolTipWrapper operator = (ToolTipWrapper)OperationComboBox.getSelectedItem();
        //adjustToolTip(operator.getItem()); 
        String op_string = operator.getItem();
        System.out.println("operatorListener got "+op_string);
        if(op_string.contains("RAND")){
            LowerBoundTextField.setVisible(true); 
            UpperBoundTextField.setVisible(true); 
        }else{
            LowerBoundTextField.setVisible(false); 
            UpperBoundTextField.setVisible(false); 
        }
        if(op_string.contains("REPLACE")){
            SymbolTextField.setVisible(true); 
        }else{
            SymbolTextField.setVisible(false); 
        }
        if(op_string.contains("HASH")){
            HashedStringTextField.setVisible(true); 
        }else{
            HashedStringTextField.setVisible(false); 
        }
        ParamPanel.revalidate();
        ParamPanel.repaint();
    }
    
    
    //Swaps artifact order in the list of artifacts and then redraws them
    void swapUpdate(String type, int rowIndex){
        //System.out.println("RowCOUNT(swap): " +dataUI.rowCount);
        dataUI.updateListofParams(uiParam.getPanelofParams());
        dataUI.swapParams(type, rowIndex);
        uiParam.loadUI();
    }
    
        //Field Getters
    public JTextField getParamIDTextField(){
        return ParamIDTextField;
    }
    public JTextField getFileTextField(){
        return FileNameTextField;
    }
    public JComboBox<ToolTipWrapper> getOperatorComboBox(){
        return OperationComboBox;
    }
    public JTextField getSymbolTextField(){
        return SymbolTextField;
    }
    public JTextField getHashedStringTextField(){
        return HashedStringTextField;
    }
    public JTextField getLowerBoundTextField(){
        return LowerBoundTextField;
    }
    public JTextField getUpperBoundTextField(){
        return UpperBoundTextField;
    }
    public JComboBox<String> getContainerComboBox(){
        return ContainerComboBox;
    }    

    //Field SETTERS
    private void setParamIDTextField(String v){
        ParamIDTextField.setText(v);
    }
    private void setFileTextField(String v){
        FileNameTextField.setText(v);
    }
    private void setSymbolTextField(String v){
        SymbolTextField.setText(v);
    }
    private void setHashedStringTextField(String v){
        HashedStringTextField.setText(v);
    }
    private void setLowerBoundTextField(String v){
        LowerBoundTextField.setText(v);
    }
    private void setUpperBoundTextField(String v){
        UpperBoundTextField.setText(v);
    }
    private void setContainerComboBox(String v){
        ContainerComboBox.setSelectedItem(v);
    }    
    private void setOperatorComboBox(String v){
        ToolTipWrapper tip = ParamReferenceStorage.getWrapper(Operator_ITEMS, v);
        OperationComboBox.setSelectedItem(tip);
    }    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ContainerComboBox;
    private javax.swing.JButton DownButton;
    private javax.swing.JTextField FileNameTextField;
    private javax.swing.JTextField HashedStringTextField;
    private javax.swing.JTextField LowerBoundTextField;
    private javax.swing.JComboBox<ToolTipWrapper> OperationComboBox;
    private javax.swing.JTextField ParamIDTextField;
    private javax.swing.JPanel ParamPanel;
    private javax.swing.JTextField SymbolTextField;
    private javax.swing.JButton UpButton;
    private javax.swing.JTextField UpperBoundTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
