FROM mfthomps/labtainer.base
LABEL description="This is base Docker image for networking Parameterized labs"
ARG lab
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-server \
    openvpn \
    wget \
    tcpdump \
    update-inetd \
    xinetd

RUN sudo mv /usr/sbin/tcpdump /usr/bin/tcpdump
ADD system/bin/togglegw.sh /usr/bin/
ADD system/bin/set_default_gw.sh /usr/bin/
