ARG registry
FROM $registry/labtainer.lamp
ADD system/etc/systemd/system/httpd.service /etc/systemd/system/
ADD system/bin/wait_param.sh /usr/bin/
ADD system/sbin/mynotify.py /sbin/mynotify.py
ADD system/etc/systemd/system/mynotify.service /etc/systemd/system/
# change link to new httpd.service file
RUN systemctl disable httpd.service
RUN systemctl enable httpd.service
RUN systemctl enable mynotify
