FROM mfthomps/labtainer.base
ARG lab
ARG labdir
ARG imagedir
ARG apt_source
ARG user_name
ADD $labdir/sys_$lab.tar.gz /
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-client
RUN apt-get install -y \
    hexedit

RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$user_name" | chpasswd
RUN adduser $user_name sudo
USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
