FROM mfthomps/labtainer.base
ARG lab
ARG labdir
ARG imagedir
ARG apt_source
ADD $labdir/sys_$lab.tar.gz /
RUN sed -i s/archive.ubuntu.com/$apt_source/ /etc/apt/sources.list
RUN apt-get update && apt-get install -y --no-install-recommends \
    openssl \
    openssh-client
RUN apt-get install -y \
    hexedit

USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
