routing-basics2.pdf: routing-basics.tex header.tex
	pdflatex -jobname=routing-basics routing-basics

clean:
	rm -fr auto
	rm -f routing-basics.aux routing-basics.log routing-basics.pdf routing-basics.dvi routing-basics.out
