routing-basics2.pdf: routing-basics2.tex header.tex
	pdflatex -jobname=routing-basics2 routing-basics2
	pdflatex -jobname=routing-basics2 routing-basics2

clean:
	rm -fr auto
	rm -f *.aux *.log *.dvi *.out
