network-basics.pdf: network-basics.tex header.tex
	pdflatex -jobname=network-basics network-basics
	pdflatex -jobname=network-basics network-basics

clean:
	rm -fr auto
	rm -f *.aux *.log *.pdf *.dvi *.out
