all: labtainer-student.pdf


labtainer-student.pdf: InstallingVB-LinuxWin.pdf labtainer-student.tex
	pdflatex labtainer-student
	pdflatex labtainer-student
clean:
	rm -fr auto
	rm -fr labtainer-student.aux labtainer-student.pdf *.ps *.dvi
