/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labtainers.mainui;

/**
 *
 * @author student
 */
public class ContainerConfigAddHosts extends javax.swing.JPanel {

    /**
     * Creates new form ContainerConfigAddHosts
     */
    private ContainerObjPanel parent;
    private LabData data;
    public ContainerConfigAddHosts(ContainerObjPanel parent, LabData data, String type, String host, String ip, String network) {
        initComponents();
        this.parent = parent;
        this.data = data;
        
        if(type.equals("ip")){
            this.AddHostHostTF.setText(host);
            this.AddHostIpTF.setText(ip);
            this.AddHostNetworkCombobox.setVisible(false);
        }
        else {
            for(int i = 0;i<data.getNetworks().size();i++){
                this.AddHostNetworkCombobox.addItem(data.getNetworks().get(i).name);
            }
            this.AddHostNetworkCombobox.setSelectedItem(network); 
            this.AddHostHostTF.setVisible(false);
            this.AddHostIpTF.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddHostIpTF = new javax.swing.JTextField();
        AddHostNetworkCombobox = new javax.swing.JComboBox<>();
        AddHostHostTF = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(545, 58));
        setMinimumSize(new java.awt.Dimension(545, 58));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(545, 58));

        AddHostIpTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        AddHostHostTF.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jButton1.setText("Delete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AddHostNetworkCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddHostHostTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(AddHostIpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AddHostNetworkCombobox, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(AddHostHostTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(AddHostIpTF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AddHostHostTF;
    private javax.swing.JTextField AddHostIpTF;
    private javax.swing.JComboBox<String> AddHostNetworkCombobox;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
