/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package labtainers.mainui;

import java.awt.Dimension;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author Daniel Liao
 */
public class ContainerConfigNetworksSubpanel extends javax.swing.JPanel {

    /**
     * Creates new form ContainerConfigNetworksSubpanel
     */
    private ContainerObjPanel parent;
    private LabData data;
    public ContainerConfigNetworksSubpanel(ContainerObjPanel parent, LabData data, String network, String ip) {
        initComponents();
        this.parent = parent;
        this.data = data;
        
        //Fill the combobox with the current list of Networks
        for(int i = 0;i<data.getNetworks().size();i++){
            this.ContainerConfigNetworksNameCombobox.addItem(data.getNetworks().get(i).name);
        }
        
//        if(!network.equals("")){
//            this.ContainerConfigNetworksNameCombobox.setSelectedItem(network);  
//        }
        this.ContainerConfigNetworksNameCombobox.setSelectedItem(network);  
        this.ContainerConfigNetworksIPTextfield.setText(ip);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ContainerConfigNetworksNameCombobox = new javax.swing.JComboBox<>();
        ContainerConfigNetworksIPTextfield = new javax.swing.JTextField();
        ContainerConfigNetworksDeleteButton = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(543, 53));
        setMinimumSize(new java.awt.Dimension(543, 53));
        setPreferredSize(new java.awt.Dimension(543, 53));

        ContainerConfigNetworksNameCombobox.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ContainerConfigNetworksIPTextfield.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        ContainerConfigNetworksDeleteButton.setText("Delete");
        ContainerConfigNetworksDeleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContainerConfigNetworksDeleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(ContainerConfigNetworksNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContainerConfigNetworksIPTextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ContainerConfigNetworksDeleteButton)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ContainerConfigNetworksDeleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(ContainerConfigNetworksIPTextfield))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(ContainerConfigNetworksNameCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ContainerConfigNetworksDeleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContainerConfigNetworksDeleteButtonActionPerformed
        JPanel containerConfigNetworksPanel = (JPanel)this.getParent();
       
           // delete the container from the list
           containerConfigNetworksPanel.remove(this);

           // Shorten the panel height holding all the containers and resize it.
           parent.containerConfigNetworksPanelLength-=53;
           containerConfigNetworksPanel.setPreferredSize(new Dimension(0,parent.containerConfigNetworksPanelLength));

           // Redraw the panel containing the list of containers
           containerConfigNetworksPanel.revalidate();
           containerConfigNetworksPanel.repaint(); 
    }//GEN-LAST:event_ContainerConfigNetworksDeleteButtonActionPerformed

    public String getNetwork(){
        return (String)(ContainerConfigNetworksNameCombobox.getSelectedItem());
    }
    
    public String getIP(){
        return ContainerConfigNetworksIPTextfield.getText();
    }
    
    protected void addNetworkToComboBox(String newNetworkName){
        ContainerConfigNetworksNameCombobox.addItem(newNetworkName);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ContainerConfigNetworksDeleteButton;
    private javax.swing.JTextField ContainerConfigNetworksIPTextfield;
    private javax.swing.JComboBox<String> ContainerConfigNetworksNameCombobox;
    // End of variables declaration//GEN-END:variables
}
