ARG registry 
FROM $registry/labtainer.network
MAINTAINER jkhosali@nps.edu
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG apt_source
ADD $labdir/sys_$lab.tar.gz /
ENV DEBIAN_FRONTEND noninteractive
RUN echo 'debconf debconf/frontend select Noninteractive' | debconf-set-selections
RUN apt-get update && apt-get install -y --no-install-recommends tshark

RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$user_name" | chpasswd
RUN chown -R $user_name:$user_name /home/$user_name
RUN adduser $user_name sudo

USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
