FROM mfthomps/labtainer.base
ARG lab
ARG labdir
ARG imagedir
ADD $labdir/$lab.tar.gz /home/ubuntu
ADD bin/funbuffer /usr/bin/

USER ubuntu
ENV HOME /home/ubuntu
RUN echo "cd" >> /home/ubuntu/.profile
RUN echo "source /home/ubuntu/.local/bin/startup.sh" >> /home/ubuntu/.profile
RUN echo "" > /home/ubuntu/.bash_logout
