FROM mfthomps/labtainer.base
MAINTAINER jkhosali@nps.edu
ARG lab
ARG labdir
ARG imagedir

RUN apt-get update && apt-get install -y --no-install-recommends telnet

ADD $labdir/sys_$lab.tar.gz /
USER ubuntu
ENV HOME /home/ubuntu
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
