FROM mfthomps/labtainer.base
#FROM mfthomps/labtainer.network
ARG lab
ARG labdir
ARG imagedir
ARG user_name
ARG apt_source

RUN apt-get update && apt-get install -y --no-install-recommends nmap telnet

ADD $labdir/sys_$lab.tar.gz /
RUN useradd -ms /bin/bash $user_name
RUN echo "$user_name:$user_name" | chpasswd
RUN adduser $user_name sudo
USER $user_name
ENV HOME /home/$user_name
ADD $labdir/$lab.tar.gz $HOME
ENTRYPOINT sudo /sbin/faux_init && bash
