package GoalsUI;

import java.awt.Component;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniel Liao
 */
public class GoalsUI extends javax.swing.JFrame {
    GoalsData dataUI;
   
    public GoalsUI() {
        initComponents();
        LabNotExist.setVisible(false);
        dataUI = new GoalsData(); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ScrollPaneOfGoals = new javax.swing.JScrollPane();
        PanelofGoals = new javax.swing.JPanel();
        UpdateButton = new javax.swing.JButton();
        RemoveAllButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        CreateButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        LabNameTextField = new javax.swing.JTextField();
        LabNotExist = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1590, 500));
        setPreferredSize(new java.awt.Dimension(1110, 389));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        ScrollPaneOfGoals.setAutoscrolls(true);
        ScrollPaneOfGoals.setMaximumSize(new java.awt.Dimension(1300, 800));

        PanelofGoals.setLayout(new javax.swing.BoxLayout(PanelofGoals, javax.swing.BoxLayout.PAGE_AXIS));
        ScrollPaneOfGoals.setViewportView(PanelofGoals);

        UpdateButton.setText("Update");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        RemoveAllButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        RemoveAllButton.setText("Remove All");
        RemoveAllButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveAllButtonActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel9.setText("Lab Name: ");

        CreateButton.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        CreateButton.setText("Create");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Goal Type");
        jLabel3.setToolTipText("The mode in which a value is found.");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Goal ID");
        jLabel1.setToolTipText("The symbolic name of the result, which will be referenced in the goals configuration file. \n\n(It must be alphanumeric, underscores permitted) ");

        LabNameTextField.setPreferredSize(new java.awt.Dimension(6, 25));
        LabNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabNameTextFieldActionPerformed(evt);
            }
        });

        LabNotExist.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabNotExist.setText("Lab does not exist!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScrollPaneOfGoals, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CreateButton)
                        .addGap(10, 10, 10)
                        .addComponent(RemoveAllButton)
                        .addGap(98, 98, 98)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabNotExist)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 344, Short.MAX_VALUE)
                        .addComponent(UpdateButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CreateButton)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(RemoveAllButton)
                        .addComponent(jLabel9)
                        .addComponent(LabNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(UpdateButton)
                        .addComponent(LabNotExist)))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScrollPaneOfGoals, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        update();
    }//GEN-LAST:event_UpdateButtonActionPerformed
    private void update(){
        if(dataUI.isLoaded())
            dataUI.writeGoalsConfig(PanelofGoals);
    }
        
    private void LabNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabNameTextFieldActionPerformed
        loadLab();
    }//GEN-LAST:event_LabNameTextFieldActionPerformed
    //Checks if the lab exists and will load lab's goals config if it does
    private void loadLab(){
        dataUI = new GoalsData(getLabName()); 
        
        if(dataUI.isLoaded()){
            LabNotExist.setVisible(false);
            goalsPanelRedraw();
        }
        else
            LabNotExist.setVisible(true);
    }  
  
    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        createFreshGoal();
    }//GEN-LAST:event_CreateButtonActionPerformed
    //Creates and loads a new goal row *Note: creating a new row does not automatically save the new row into the GoalsData(acti)
    private void createFreshGoal(){
        if(dataUI.isLoaded()){
            dataUI.increaseRowCount();
            GoalPanels newGoal = new GoalPanels(this, dataUI);
            PanelofGoals.add(newGoal);
            PanelofGoals.revalidate();
            PanelofGoals.repaint(); 
        }
    }
        
    private void RemoveAllButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveAllButtonActionPerformed
        removeAllButton();
    }//GEN-LAST:event_RemoveAllButtonActionPerformed
    private void removeAllButton(){
        if(dataUI.isLoaded()){
           if(JOptionPane.showConfirmDialog(null, "Are you sure you want to remove all?") == JOptionPane.YES_OPTION){
                removeAllGoals();
                dataUI.resetData();
           }          
        }
    }
       
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        checkUnsavedChangesMade();
    }//GEN-LAST:event_formWindowClosing
    //Check if the the current state of the UI matches with what's saved in the goals.config
    void checkUnsavedChangesMade(){
        if(dataUI.isLoaded()){
            dataUI.updateListofGoals(PanelofGoals);
            
            if(GoalsData.goalValuesDiffer(dataUI.getListofGoals(), dataUI.getGoalValuesOfConfigFile())){
                int confirmed = JOptionPane.showConfirmDialog(null, 
                "There are Unsaved Changes. Are you sure you want to exit the program?", "Unsaved Changes",
                JOptionPane.YES_NO_OPTION);

                if (confirmed == JOptionPane.YES_OPTION) 
                  dispose();
                else
                    setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            }
            else
                dispose();
        }
    }
        
//General Methods
    //Updates the list of goals and redraws them on screen
    void refresh(){
       dataUI.updateListofGoals(PanelofGoals);       
       goalsPanelRedraw();
    }
    
    //Redraws the goals Panel
    void goalsPanelRedraw(){
        removeAllGoals();               
        for(int i=0; i < dataUI.getListofGoals().size(); i++)
            loadGoal(dataUI.getListofGoals().get(i), i+1);
    }
     
    //Removes all the goal lines for the lab *note: this doesn't update results.config until the user hits the update button
    private void removeAllGoals(){
        Component[] componentList = PanelofGoals.getComponents();
        for(Component c: componentList)
            PanelofGoals.remove(c);
        PanelofGoals.revalidate();
        PanelofGoals.repaint();
    }
  
    //Load's the goals into GUI
    private void loadGoal(GoalValues goalVal, int rowNum){
        GoalPanels newGoal = new GoalPanels(this, dataUI, goalVal, rowNum);
        PanelofGoals.add(newGoal);        
        PanelofGoals.revalidate();
        PanelofGoals.repaint(); 
    }
      
    
    
    //Gets the labname
    private String getLabName(){ 
        return LabNameTextField.getText();
    }
    
    //Gets the panel holding the goals
    protected JPanel getPanelofGoals(){
        return PanelofGoals;
    }

        
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GoalsUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
       //</editor-fold>
       //</editor-fold>
       
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            GoalsUI newGoalsUI = new GoalsUI();
            newGoalsUI.setSize(1000, 1000);
            newGoalsUI.setVisible(true);
        });
    }

      
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField LabNameTextField;
    private javax.swing.JLabel LabNotExist;
    private javax.swing.JPanel PanelofGoals;
    private javax.swing.JButton RemoveAllButton;
    private javax.swing.JScrollPane ScrollPaneOfGoals;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
